#!/usr/bin/env bash
project_dir="$(cd .; pwd)"

_stack_exists() {
  template_name=$1
  aws cloudformation describe-stacks  \
    --stack-name "$1"      \
    --region "$2"   \
    &> /dev/null
  return $?
}

app_name="$1"
region="$2"
template_name="$3"
parameter_name="$4"

STACK_NAME="${app_name}"

template="file://${project_dir}/cloudformation/${template_name}"
parameters="file://${project_dir}/cloudformation/${parameter_name}"


_stack_exists "${STACK_NAME}" "${region}" && action="update" || action="create"
echo "Waiting for stack ${STACK_NAME} to be ${action}d."

message=$(
  aws cloudformation ${action}-stack        \
    --stack-name "${STACK_NAME}"            \
    --template-body "${template}"           \
    --parameters "$(echo ${parameters})"     \
    --capabilities CAPABILITY_IAM \
    --region "${region}" \
    2>&1
)
exit_code="$?"
[[ "${message}" =~ "No updates are to be performed" ]] && exit 0
echo ${message}
[[ ${exit_code} -ne 0 ]] && exit 1

aws cloudformation wait stack-${action}-complete \
  --stack-name ${template_name} \
  --region "${region}"
