#!/usr/bin/env bash
usage(){
  echo "Usage: $0 <reset|start|stop>"
  exit 1
}

update_host(){
  sed -i -e '/local.personal.vpn/d' /etc/hosts
  echo "$1 local.personal.vpn" >> /etc/hosts
}

query_vpn_ip(){
  echo `aws ec2 describe-instances --filters Name=tag:aws:cloudformation:stack-name,Values=personal-vpn Name=instance-state-name,Values=running --query "Reservations[0].Instances[0].PublicIpAddress"`
}

query_autoscaling_name(){
  echo `aws cloudformation describe-stacks --stack-name personal-vpn --query "Stacks[0].Outputs[?OutputKey=='AutoScalingName']|[0].OutputValue"`
}

reset_vpn_ip(){
  local ip=`query_vpn_ip`
  if [[ -z "$ip" || "$ip" == "null" ]]; then
    echo "Failed to fetch vpn ip address"
    exit 1
  fi

  update_host ${ip//\"}
}

stop_vpn_server(){
  local name=`query_autoscaling_name`
  if [[ -z "${name}" || "$ip" == "null" ]]; then
    echo "Failed to fetch autoscaling name"
    exit 1
  fi
  aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${name//\"} --min-size 0 --desired-capacity 0
}

start_vpn_server(){
  local name=`query_autoscaling_name`
  if [[ -z "$name" || "$ip" == "null" ]]; then
    echo "Failed to fetch autoscaling name"
    exit 1
  fi
  aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${name//\"} --min-size 1 --desired-capacity 1
}

main(){
  if [[ -z "$AWS_DEFAULT_REGION" ]]; then
    echo "Please set AWS_DEFAULT_REGION"
    exit 1
  fi

  case $1 in
    "reset")
      reset_vpn_ip
      ;;
    "start")
      start_vpn_server
      ;;
    "stop")
      stop_vpn_server
      ;;
    *)
      usage
      ;;
  esac
}

main $@
